//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordMake.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int 显示放大倍数 {
            get {
                return ((int)(this["显示放大倍数"]));
            }
            set {
                this["显示放大倍数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 扫描线方向水平 {
            get {
                return ((bool)(this["扫描线方向水平"]));
            }
            set {
                this["扫描线方向水平"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 水平扫描从左到右 {
            get {
                return ((bool)(this["水平扫描从左到右"]));
            }
            set {
                this["水平扫描从左到右"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 竖直扫描从上到下 {
            get {
                return ((bool)(this["竖直扫描从上到下"]));
            }
            set {
                this["竖直扫描从上到下"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 扫描线非整字节的用位０填充 {
            get {
                return ((bool)(this["扫描线非整字节的用位０填充"]));
            }
            set {
                this["扫描线非整字节的用位０填充"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 输出字节顺序高位在前 {
            get {
                return ((bool)(this["输出字节顺序高位在前"]));
            }
            set {
                this["输出字节顺序高位在前"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 文件头 {
            get {
                return ((string)(this["文件头"]));
            }
            set {
                this["文件头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 文件尾 {
            get {
                return ((string)(this["文件尾"]));
            }
            set {
                this["文件尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t[] ={\r\n")]
        public string 段标识 {
            get {
                return ((string)(this["段标识"]));
            }
            set {
                this["段标识"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 添加段唯一标识 {
            get {
                return ((bool)(this["添加段唯一标识"]));
            }
            set {
                this["添加段唯一标识"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("byte Image")]
        public string 段头 {
            get {
                return ((string)(this["段头"]));
            }
            set {
                this["段头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("};")]
        public string 段尾 {
            get {
                return ((string)(this["段尾"]));
            }
            set {
                this["段尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x")]
        public string 数据头 {
            get {
                return ((string)(this["数据头"]));
            }
            set {
                this["数据头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string 数据尾 {
            get {
                return ((string)(this["数据尾"]));
            }
            set {
                this["数据尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//")]
        public string 注解头 {
            get {
                return ((string)(this["注解头"]));
            }
            set {
                this["注解头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 注解尾 {
            get {
                return ((string)(this["注解尾"]));
            }
            set {
                this["注解尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 数据格式十六进制 {
            get {
                return ((bool)(this["数据格式十六进制"]));
            }
            set {
                this["数据格式十六进制"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font 字体 {
            get {
                return ((global::System.Drawing.Font)(this["字体"]));
            }
            set {
                this["字体"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point 字模偏移 {
            get {
                return ((global::System.Drawing.Point)(this["字模偏移"]));
            }
            set {
                this["字模偏移"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 自动字体大小 {
            get {
                return ((bool)(this["自动字体大小"]));
            }
            set {
                this["自动字体大小"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 12")]
        public global::System.Drawing.Size 字模大小 {
            get {
                return ((global::System.Drawing.Size)(this["字模大小"]));
            }
            set {
                this["字模大小"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 数据段分行 {
            get {
                return ((bool)(this["数据段分行"]));
            }
            set {
                this["数据段分行"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 数据行头 {
            get {
                return ((string)(this["数据行头"]));
            }
            set {
                this["数据行头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string 数据行尾 {
            get {
                return ((string)(this["数据行尾"]));
            }
            set {
                this["数据行尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string 每行数据位 {
            get {
                return ((string)(this["每行数据位"]));
            }
            set {
                this["每行数据位"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Info")]
        public global::System.Drawing.Color 已点亮区域LCD颜色 {
            get {
                return ((global::System.Drawing.Color)(this["已点亮区域LCD颜色"]));
            }
            set {
                this["已点亮区域LCD颜色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color 未点亮区域LCD颜色 {
            get {
                return ((global::System.Drawing.Color)(this["未点亮区域LCD颜色"]));
            }
            set {
                this["未点亮区域LCD颜色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 0, 0, 255")]
        public global::System.Drawing.Color 字符线框颜色 {
            get {
                return ((global::System.Drawing.Color)(this["字符线框颜色"]));
            }
            set {
                this["字符线框颜色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, 8")]
        public global::System.Drawing.Point 主窗口位置 {
            get {
                return ((global::System.Drawing.Point)(this["主窗口位置"]));
            }
            set {
                this["主窗口位置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{")]
        public string 自动生成段头 {
            get {
                return ((string)(this["自动生成段头"]));
            }
            set {
                this["自动生成段头"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("};")]
        public string 自动生成段尾 {
            get {
                return ((string)(this["自动生成段尾"]));
            }
            set {
                this["自动生成段尾"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 自动模式输出索引偏移 {
            get {
                return ((string)(this["自动模式输出索引偏移"]));
            }
            set {
                this["自动模式输出索引偏移"] = value;
            }
        }
    }
}
