//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordMake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordMake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BoldHS {
            get {
                object obj = ResourceManager.GetObject("BoldHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomArrow2HS {
            get {
                object obj = ResourceManager.GetObject("BottomArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToNextHS {
            get {
                object obj = ResourceManager.GetObject("GoToNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToPrevious {
            get {
                object obj = ResourceManager.GetObject("GoToPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItalicHS {
            get {
                object obj = ResourceManager.GetObject("ItalicHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LiftArrow2HS {
            get {
                object obj = ResourceManager.GetObject("LiftArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Offset {
            get {
                object obj = ResourceManager.GetObject("Offset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeatHS {
            get {
                object obj = ResourceManager.GetObject("RepeatHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow2HS {
            get {
                object obj = ResourceManager.GetObject("RightArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopArrow2HS {
            get {
                object obj = ResourceManager.GetObject("TopArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordmake {
            get {
                object obj = ResourceManager.GetObject("wordmake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wordmake1 {
            get {
                object obj = ResourceManager.GetObject("wordmake1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上下偏移.
        /// </summary>
        internal static string 上下偏移 {
            get {
                return ResourceManager.GetString("上下偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下划线.
        /// </summary>
        internal static string 下划线 {
            get {
                return ResourceManager.GetString("下划线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏移.
        /// </summary>
        internal static string 偏移 {
            get {
                return ResourceManager.GetString("偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加粗.
        /// </summary>
        internal static string 加粗 {
            get {
                return ResourceManager.GetString("加粗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载配置文件....
        /// </summary>
        internal static string 加载配置文件 {
            get {
                return ResourceManager.GetString("加载配置文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        internal static string 字体 {
            get {
                return ResourceManager.GetString("字体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字号.
        /// </summary>
        internal static string 字号 {
            get {
                return ResourceManager.GetString("字号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左右偏移.
        /// </summary>
        internal static string 左右偏移 {
            get {
                return ResourceManager.GetString("左右偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斜体.
        /// </summary>
        internal static string 斜体 {
            get {
                return ResourceManager.GetString("斜体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示缩放.
        /// </summary>
        internal static string 显示缩放 {
            get {
                return ResourceManager.GetString("显示缩放", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成字模高宽.
        /// </summary>
        internal static string 生成字模高宽 {
            get {
                return ResourceManager.GetString("生成字模高宽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件|*.config.
        /// </summary>
        internal static string 配置文件Filter {
            get {
                return ResourceManager.GetString("配置文件Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件另存为....
        /// </summary>
        internal static string 配置文件另存为 {
            get {
                return ResourceManager.GetString("配置文件另存为", resourceCulture);
            }
        }
    }
}
