//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordMake.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordMake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BoldHS {
            get {
                object obj = ResourceManager.GetObject("BoldHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomArrow2HS {
            get {
                object obj = ResourceManager.GetObject("BottomArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToNextHS {
            get {
                object obj = ResourceManager.GetObject("GoToNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToPrevious {
            get {
                object obj = ResourceManager.GetObject("GoToPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItalicHS {
            get {
                object obj = ResourceManager.GetObject("ItalicHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LiftArrow2HS {
            get {
                object obj = ResourceManager.GetObject("LiftArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Offset {
            get {
                object obj = ResourceManager.GetObject("Offset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RepeatHS {
            get {
                object obj = ResourceManager.GetObject("RepeatHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow2HS {
            get {
                object obj = ResourceManager.GetObject("RightArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopArrow2HS {
            get {
                object obj = ResourceManager.GetObject("TopArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordmake {
            get {
                object obj = ResourceManager.GetObject("wordmake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wordmake1 {
            get {
                object obj = ResourceManager.GetObject("wordmake1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 上下偏移 的本地化字符串。
        /// </summary>
        internal static string 上下偏移 {
            get {
                return ResourceManager.GetString("上下偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        internal static string 下划线 {
            get {
                return ResourceManager.GetString("下划线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏移 的本地化字符串。
        /// </summary>
        internal static string 偏移 {
            get {
                return ResourceManager.GetString("偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        internal static string 加粗 {
            get {
                return ResourceManager.GetString("加粗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载配置文件... 的本地化字符串。
        /// </summary>
        internal static string 加载配置文件 {
            get {
                return ResourceManager.GetString("加载配置文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string 字体 {
            get {
                return ResourceManager.GetString("字体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        internal static string 字号 {
            get {
                return ResourceManager.GetString("字号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右偏移 的本地化字符串。
        /// </summary>
        internal static string 左右偏移 {
            get {
                return ResourceManager.GetString("左右偏移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string 斜体 {
            get {
                return ResourceManager.GetString("斜体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示缩放 的本地化字符串。
        /// </summary>
        internal static string 显示缩放 {
            get {
                return ResourceManager.GetString("显示缩放", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成字模高宽 的本地化字符串。
        /// </summary>
        internal static string 生成字模高宽 {
            get {
                return ResourceManager.GetString("生成字模高宽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件|*.config 的本地化字符串。
        /// </summary>
        internal static string 配置文件Filter {
            get {
                return ResourceManager.GetString("配置文件Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件另存为... 的本地化字符串。
        /// </summary>
        internal static string 配置文件另存为 {
            get {
                return ResourceManager.GetString("配置文件另存为", resourceCulture);
            }
        }
    }
}
